def on_button_pressed_a():
    strip.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.show_icon(IconNames.STICK_FIGURE)
    kitronik_servo_lite.drive_backwards(5)
    kitronik_servo_lite.turn_left(90)
    kitronik_servo_lite.drive_backwards(5)
    kitronik_servo_lite.turn_left(90)
    kitronik_servo_lite.drive_backwards(5)
    kitronik_servo_lite.turn_left(90)
    kitronik_servo_lite.drive_backwards(5)
    kitronik_servo_lite.turn_left(90)
    strip.clear()
    strip.show()
    basic.clear_screen()
input.on_button_pressed(Button.A, on_button_pressed_a)

strip: neopixel.Strip = None
strip = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
strip.show_rainbow(1, 360)
strip.show()
basic.show_string("Ahoj! Volam sa ZAPET")
kitronik_servo_lite.turn_left(360)
strip.clear()
strip.show()