input.onButtonPressed(Button.A, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.showIcon(IconNames.StickFigure)
    kitronik_servo_lite.driveBackwards(30)
    kitronik_servo_lite.turnLeft(90)
    kitronik_servo_lite.driveBackwards(30)
    kitronik_servo_lite.turnLeft(90)
    kitronik_servo_lite.driveBackwards(30)
    kitronik_servo_lite.turnLeft(90)
    kitronik_servo_lite.driveBackwards(30)
    kitronik_servo_lite.turnLeft(90)
    strip.clear()
    strip.show()
    basic.clearScreen()
})
input.onLogoEvent(TouchButtonEvent.Touched, function () {
    for (let index = 0; index < 4; index++) {
        strip.showRainbow(1, 360)
        basic.showIcon(IconNames.Heart)
        basic.pause(500)
        basic.showIcon(IconNames.SmallHeart)
        basic.pause(500)
        strip.clear()
        strip.show()
        basic.clearScreen()
    }
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 4; index++) {
        basic.showIcon(IconNames.StickFigure)
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
        basic.pause(500)
        strip.clear()
        strip.show()
        basic.showIcon(IconNames.Heart)
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        basic.pause(500)
        strip.clear()
        strip.show()
        basic.showIcon(IconNames.Happy)
        strip.showColor(neopixel.colors(NeoPixelColors.Green))
        basic.pause(500)
        strip.clear()
        strip.show()
        basic.clearScreen()
    }
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
strip.showRainbow(1, 360)
strip.easeBrightness()
basic.pause(1000)
strip.clear()
strip.show()
basic.showString("Ahoj!Volam sa ZAPET")
kitronik_servo_lite.turnLeft(270)
